import esbuild from 'esbuild'
import process from 'process'
import sveltePlugin from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'
import fs from 'fs'
import path from 'path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
// watch/dev → staging (fsky.top); production build → production (mdfriday.com)
// Override: MDF_CF_ENV=local|staging|production
const defaultCfEnv = process.env.MDF_CF_ENV || (prod ? 'production' : 'staging')
// Change this to your local Obsidian plugin path for development
const pluginDir = path.join(process.env.HOME || '', 'Desktop', 'obsidian-test', '.obsidian', 'plugins', 'mdfriday-publish');

const renameCssFile = (cssPath, targetPath) => {
	try {
		if (fs.existsSync(cssPath)) {
			fs.renameSync(cssPath, targetPath);
			console.log(`✓ Renamed CSS to ${targetPath}`);
			return true;
		}
	} catch (error) {
		console.error(`Failed to rename CSS file: ${error.message}`);
	}
	return false;
};

const cssRenamePlugin = {
	name: 'css-rename',
	setup(build) {
		build.onEnd((result) => {
			if (result && result.metafile) {
				const outputs = Object.keys(result.metafile.outputs).filter(file => file.endsWith('.css'));
				outputs.forEach(cssFile => {
					if (cssFile.includes('main.css')) {
						const cssPath = path.resolve(cssFile);
						const targetPath = prod
							? path.join(process.cwd(), 'styles.css')
							: path.join(pluginDir, 'styles.css');
						renameCssFile(cssPath, targetPath);
					}
				});
			}
		});
	}
};

const externals = [
	'obsidian',
	'electron',
	'crypto',
	'@codemirror/autocomplete',
	'@codemirror/closebrackets',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/comment',
	'@codemirror/fold',
	'@codemirror/gutter',
	'@codemirror/highlight',
	'@codemirror/history',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/matchbrackets',
	'@codemirror/panel',
	'@codemirror/rangeset',
	'@codemirror/rectangular-selection',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/stream-parser',
	'@codemirror/text',
	'@codemirror/tooltip',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	'fs',
	'fs/promises',
	'path',
	'net',
	'tls',
	'stream',
	'stream/promises',
	'http',
	'https',
	'util',
	'os',
	'process',
	'url',
	'worker_threads',
	'child_process',
	'node:fs',
	'node:fs/promises',
	'node:path',
	'node:stream',
	'node:process',
	'node:url',
	'node:worker_threads',
	'node:child_process',
];

const buildOptions = {
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		__MDF_DEFAULT_CF_ENV__: JSON.stringify(defaultCfEnv),
		global: 'window',
	},
	external: externals,
	alias: {
		// Node 'events' → browser polyfill (Foundry / chokidar)
		'events': 'events',
	},
	platform: 'browser',
	mainFields: ['browser', 'module', 'main'],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	metafile: true,
	plugins: [
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: {
				css: 'injected',
				compatibility: {
					componentApi: 4
				}
			},
		}),
		cssRenamePlugin,
	],
	outfile: prod ? 'main.js' : path.join(pluginDir, 'main.js'),
};

buildOptions.loader = buildOptions.loader || {};
buildOptions.loader['.css'] = 'css';

if (prod) {
	esbuild
		.build(buildOptions)
		.then(() => {
		console.log('✓ Build completed successfully')
		console.log(`  default Cloudflare env: ${defaultCfEnv}`)
	})
		.catch(() => process.exit(1));
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
